-- MySQL Script generated by MySQL Workbench
-- Wed Feb  6 22:26:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_polita
-- -----------------------------------------------------
-- Base de datos para el proyecto polita

-- -----------------------------------------------------
-- Schema db_polita
--
-- Base de datos para el proyecto polita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_polita` DEFAULT CHARACTER SET utf8 ;
USE `db_polita` ;

-- -----------------------------------------------------
-- Table `db_polita`.`tbl_question_answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_polita`.`tbl_question_answer` (
  `id_qa` INT NOT NULL AUTO_INCREMENT,
  `ds_question` VARCHAR(455) NULL,
  `ds_answer` VARCHAR(455) NULL,
  `tbl_question_answercol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_qa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_polita`.`tbl_frequently_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_polita`.`tbl_frequently_question` (
  `id_fq` INT NOT NULL AUTO_INCREMENT,
  `ds_email` VARCHAR(100) NULL,
  `ds_identification` VARCHAR(45) NULL,
  `ds_name` VARCHAR(45) NULL,
  `ds_question` VARCHAR(455) NULL,
  PRIMARY KEY (`id_fq`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
